version: '3.8'

services:
  # Backend Python
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://sacsmax:sacsmax@postgres:5432/sacsmax
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
      - SECRET_KEY=dev-secret-key-change-in-production
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - uploads:/app/uploads
      - logs:/app/logs
      - whatsapp_sessions:/app/whatsapp_sessions

  # WhatsApp Web.js
  whatsapp:
    build: ./backend/whatsapp-web.js
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend/whatsapp-web.js:/app
      - whatsapp_sessions:/app/sessions

  # PostgreSQL
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=sacsmax
      - POSTGRES_USER=sacsmax
      - POSTGRES_PASSWORD=sacsmax
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Frontend (opcional - pode rodar localmente)
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    environment:
      - API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:
  uploads:
  logs:
  whatsapp_sessions:

