[phases.setup]
aptPkgs = ["python3-pip"]

[phases.install]
cmds = ["pip install -r requirements.txt", "npm install"]

[phases.build]
cmds = ["echo 'Build complete for Python and Node.js'"]

[start]
cmd = "python3 railway_startup.py & node whatsapp-server-simple.js"


