[phases.setup]
nixPkgs = ["python3", "nodejs", "git"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "npm install"
]

[phases.build]
cmds = [
  "echo 'Build completed'"
]

[start]
cmd = "python railway_startup.py"
