[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "docker-entrypoint.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { RAILWAY_ENVIRONMENT = "production", NODE_ENV = "production" }

[environments.development]
variables = { RAILWAY_ENVIRONMENT = "development", NODE_ENV = "development" }
