[build]
builder = "nixpacks"

[deploy]
startCommand = "python backend/main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
name = "sacmax-backend"
internal_port = 5000
external_port = 80

[env]
BACKEND_PORT = "5000"
PYTHON_VERSION = "3.11"
WEBHOOK_SECRET = "sacmax_webhook_secret_2024"

# Configurações de memória e persistência
WHATSAPP_STORAGE_ENABLED = "true"
WHATSAPP_RETENTION_DAYS = "15"
WHATSAPP_MAX_MESSAGES_PER_CHAT = "1000"
WHATSAPP_CLEANUP_INTERVAL_HOURS = "6"

# Configurações de volume (se necessário)
# VOLUME_PATH = "/app/data"
