[phases.setup]
nixPkgs = ["python310", "gcc-unwrapped"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["mkdir -p uploads"]

[start]
cmd = "gunicorn main:app --bind 0.0.0.0:$PORT --workers 4"
