[phases.setup]
nixPkgs = ["python311", "postgresql", "gcc", "gcc-unwrapped", "libpq-dev"]

[phases.install]
cmds = [
    "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = [
    "mkdir -p uploads logs whatsapp_sessions"
]

[start]
cmd = "gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
