version: '3.8'

services:
  sacsmax-automation:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: sacsmax-automation
    ports:
      - "3000:3000"
    volumes:
      - ../uploads:/app/uploads
      - ../logs:/app/logs
      - ../config:/app/config
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - sacsmax-network

networks:
  sacsmax-network:
    driver: bridge